 services:
  api:
    image: python:3.14-slim
    container_name: fabryka-api
    restart: unless-stopped
    working_dir: /app

    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./apps/api:/app
    command: >
      sh -c "python -m venv venv &&
      ./venv/bin/pip install -r /app/requirements.txt &&
      ./venv/bin/uvicorn src.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
